/**
 * Loop Compute — the deterministic agent-assist work unit, isomorphic.
 *
 * This is the exact algorithm the native device nodes run (the reference
 * implementation lives in the blockchain-compute repo, src/loop/agent-work.ts +
 * src/shared/jobs.ts). It is ported here so it runs in TWO more places:
 *
 *  1. the browser — the public beta node on /compute does the work client-side;
 *  2. the ingest API — the server RECOMPUTES the result and only accepts a
 *     public submission whose resultHash matches (proof-of-honest-work, since
 *     the job is deterministic).
 *
 * Parity is locked by lib/compute-work.test.ts against a fixture generated by
 * the reference implementation — do not "improve" the text or the hashing here
 * without shipping the same change to the device nodes, or every cross-check
 * fails. sha256 uses WebCrypto (async), available in browsers and Node ≥ 18.
 */

export interface AgentAssistPayload {
  kind: "agent_assist";
  projectKey: string;
  taskId: number;
  title: string;
  detail: string;
  status: string;
  priority: number;
  category: string;
  repo?: string | null;
}

export interface AgentAssistResult {
  taskId: number;
  projectKey: string;
  title: string;
  prepBrief: string;
  keywords: string[];
  checklist: string[];
  complexity: "S" | "M" | "L" | "XL";
  estimateMinutes: number;
  wordCount: number;
  detailHash: string;
  acceptanceHints: string[];
  processedAt: string;
  deviceNote: string;
}

async function sha256Hex(s: string): Promise<string> {
  const buf = await globalThis.crypto.subtle.digest("SHA-256", new TextEncoder().encode(s));
  return Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

const STOP = new Set(
  "a an the and or for to of in on with is are be this that it as by from we you our their will can should must".split(
    " "
  )
);

export function extractKeywords(text: string, n = 8): string[] {
  const counts = new Map<string, number>();
  for (const raw of text.toLowerCase().split(/[^a-z0-9+#./-]+/)) {
    const w = raw.trim();
    if (w.length < 3 || STOP.has(w)) continue;
    counts.set(w, (counts.get(w) ?? 0) + 1);
  }
  return Array.from(counts.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, n)
    .map(([w]) => w);
}

export function scoreComplexity(
  title: string,
  detail: string
): { complexity: AgentAssistResult["complexity"]; estimateMinutes: number } {
  const words = `${title} ${detail}`.split(/\s+/).filter(Boolean).length;
  if (words < 40) return { complexity: "S", estimateMinutes: 30 };
  if (words < 90) return { complexity: "M", estimateMinutes: 90 };
  if (words < 160) return { complexity: "L", estimateMinutes: 180 };
  return { complexity: "XL", estimateMinutes: 360 };
}

export function buildChecklist(title: string, detail: string): string[] {
  const items = [
    `Clarify success criteria for: ${title.slice(0, 80)}`,
    "Read related code / existing UI before editing",
    "Implement smallest shippable change",
    "Add or update tests / typecheck",
    "Verify on local or preview",
  ];
  if (/treasury|wallet|sol|on-chain|fee/i.test(detail)) {
    items.push("Double-check money-path guardrails (no unguarded transfers)");
  }
  if (/ui|page|landing|mobile|nav/i.test(detail + title)) {
    items.push("Check mobile + desktop layout");
  }
  if (/agent|tick|cron/i.test(detail + title)) {
    items.push("Confirm maker≠checker / budget hard-stop still hold");
  }
  return items;
}

export function acceptanceHints(detail: string): string[] {
  const hints: string[] = [];
  if (/test/i.test(detail)) hints.push("Must include automated test");
  if (/holder|trust|transpar/i.test(detail)) hints.push("Must improve holder-facing honesty");
  if (/mobile/i.test(detail)) hints.push("Must work on small screens");
  if (/endpoint|api/i.test(detail)) hints.push("Must keep public API read-only safe");
  if (hints.length === 0) hints.push("Ship minimal green change with clear description");
  return hints;
}

/** The deterministic work unit — identical output on every honest device. */
export async function executeAgentAssist(payload: AgentAssistPayload): Promise<AgentAssistResult> {
  const text = `${payload.title}\n${payload.detail}`;
  const { complexity, estimateMinutes } = scoreComplexity(payload.title, payload.detail);
  const keywords = extractKeywords(text);
  const checklist = buildChecklist(payload.title, payload.detail);
  const hints = acceptanceHints(payload.detail);
  const prepBrief = [
    `## Agent assist brief — ${payload.projectKey} task #${payload.taskId}`,
    ``,
    `**Title:** ${payload.title}`,
    `**Priority:** ${payload.priority} · **Complexity:** ${complexity} (~${estimateMinutes}m)`,
    `**Keywords:** ${keywords.join(", ") || "—"}`,
    ``,
    `### Detail`,
    payload.detail.slice(0, 1200),
    ``,
    `### Checklist`,
    ...checklist.map((c, i) => `${i + 1}. ${c}`),
    ``,
    `### Acceptance hints`,
    ...hints.map((h) => `- ${h}`),
    ``,
    `_Prepared by Loop Compute device for the project agent._`,
  ].join("\n");

  return {
    taskId: payload.taskId,
    projectKey: payload.projectKey,
    title: payload.title,
    prepBrief,
    keywords,
    checklist,
    complexity,
    estimateMinutes,
    wordCount: text.split(/\s+/).filter(Boolean).length,
    detailHash: await sha256Hex(text),
    acceptanceHints: hints,
    processedAt: "",
    deviceNote: "",
  };
}

// Key-sorted JSON so the hash is stable across JS engines and field order.
function stableStringify(value: unknown): string {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(stableStringify).join(",")}]`;
  }
  const obj = value as Record<string, unknown>;
  const keys = Object.keys(obj).sort();
  return `{${keys.map((k) => `${JSON.stringify(k)}:${stableStringify(obj[k])}`).join(",")}}`;
}

/** Proof hash of a deterministic result — what devices submit and verifiers recompute. */
export function hashResult(result: Record<string, unknown>): Promise<string> {
  return sha256Hex(stableStringify(result));
}

/**
 * One call for both sides: run the work and hash the proof. The browser node
 * submits `resultHash`; the ingest API recomputes it from the task row and
 * rejects mismatches — public devices can't spoof briefs.
 */
export async function runAssist(
  payload: AgentAssistPayload
): Promise<{ result: AgentAssistResult; resultHash: string }> {
  const result = await executeAgentAssist(payload);
  return { result, resultHash: await hashResult(result as unknown as Record<string, unknown>) };
}
