import { describe, it, expect } from "vitest";
import { executeAgentAssist, hashResult, runAssist, type AgentAssistPayload } from "./compute-work";
import fixture from "./compute-work.fixture.json";

// Parity lock against the reference implementation (blockchain-compute repo,
// src/loop/agent-work.ts + src/shared/jobs.ts). The fixture was generated BY
// that implementation — if this port drifts by a single character, the hash
// changes and every device/server cross-check would fail. Regenerate the
// fixture only when the reference algorithm itself changes, never to make a
// local edit pass.
describe("compute-work parity with the device-node reference", () => {
  const payload = fixture.payload as AgentAssistPayload;

  it("reproduces the reference prepBrief byte-for-byte", async () => {
    const result = await executeAgentAssist(payload);
    expect(result.prepBrief).toBe(fixture.result.prepBrief);
  });

  it("reproduces every deterministic field", async () => {
    const result = await executeAgentAssist(payload);
    expect(result).toEqual(fixture.result);
  });

  it("reproduces the reference resultHash", async () => {
    const { resultHash } = await runAssist(payload);
    expect(resultHash).toBe(fixture.resultHash);
  });

  it("hash is stable regardless of key insertion order", async () => {
    const a = await hashResult({ b: 1, a: [2, { d: 3, c: 4 }] });
    const b = await hashResult({ a: [2, { c: 4, d: 3 }], b: 1 });
    expect(a).toBe(b);
  });

  it("detects a tampered brief via the hash", async () => {
    const result = await executeAgentAssist(payload);
    const tampered = { ...result, prepBrief: result.prepBrief + " (edited)" };
    expect(await hashResult(tampered as unknown as Record<string, unknown>)).not.toBe(
      fixture.resultHash
    );
  });
});
